name: Build Bundle
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create bundle
        run: |
          mkdir -p dist
          zip -r dist/canonlock_noelictus_latest.zip             lore rules gameplay scenes index.html style.css README.md CHANGELOG.md HOW_TO_AUTOMATE.md tools || true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: canonlock_noelictus_latest
          path: dist/canonlock_noelictus_latest.zip
  release-on-tag:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create bundle
        run: |
          mkdir -p dist
          zip -r dist/canonlock_noelictus_${{ github.ref_name }}.zip             lore rules gameplay scenes index.html style.css README.md CHANGELOG.md HOW_TO_AUTOMATE.md tools || true
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/canonlock_noelictus_${{ github.ref_name }}.zip
